### PR TITLE
feat: add emulator contextmanager

### LINKED ISSUE #24: Create contextmanager for emulator
Design suggestion for encapsulating emulator start and kill functions

```python
from contextlib import contextmanager

@contextmanager
def create_emulator():
    # Code to acquire resource, e.g.:
    emulator = cls._start_emulator()
    try:
        yield emulator
    finally:
        # Code to release resource, e.g.:
        cls._kill_emulator()
#--snip--
def phase_two_execution(cls, timeout, tool_set, tools, repetition):
#--snip
    with create_emulator() as emulator:
           # Resource is released at the end of this block,
           # even if code in the block raises an exception
```

Source: https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager

### PR DESCRIPTION
**Pull request by thlmenezes**
fixes #24

### CODE REVIEW

**Comment by rbonifacio** [comment]
@thlmenezes , just as a clarification, this PR deals with exception handling, right?

**Comment by rbonifacio** [comment]
@thlmenezes, using this feature of context manager, what happens when we are cannot "yield" an emulator?

**Comment by thlmenezes** [comment]
> @thlmenezes, using this feature of context manager, what happens when we are cannot "yield" an emulator?

If a Exception occurs, it should attempt to kill the emulator before breaking the benchmark' execution

**Comment by thlmenezes** [comment]
> @thlmenezes, using this feature of context manager, what happens when we are cannot "yield" an emulator?

It executes the finally clause, from the python docs:

> " If finally is present, it specifies a ‘cleanup’ handler. The try clause is executed, including any except and else clauses. If an exception occurs in any of the clauses and is not handled, the exception is temporarily saved. The finally clause is executed. If there is a saved exception it is re-raised at the end of the finally clause. If the finally clause raises another exception, the saved exception is set as the context of the new exception. If the finally clause executes a return, break or continue statement, the saved exception is discarded"

Source:
https://docs.python.org/3/reference/compound_stmts.html?highlight=finally#the-try-statement

**Pull request merged**
